---
  - name: Config Web VMs with Docker
    hosts: webservers
    become: true
    tasks

    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install Python Docker Module
      apt:
        name: docker
        state: present

    - name: Download and Launch a Docker Web Container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80